name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Prepare GTest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Configure project using CMake
        run: |
          mkdir -p build
          cd build
          cmake ../src

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
