name: Build And Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build Google Test
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib

      - name: Build and Run Tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
